### ISSUE TITLE
localStorage可手工修改问题

### ISSUE THREAD

**Issue by Skkypy** [WeBankBlockchain/WeBASE-Web#247]
`localStorage`内容可手工直接修改。
例如，普通用户`visitor`登录运营平台后，修改`root`值为`admin`，则刷新页面直接获得管理员权限。
建议增加修改的监听。

**Comment by CodingCattwo** [comment]
后台通过token确认管理员的权限，修改root值后仅改变前端页面的展示，但无法获取管理员的数据
