### ISSUE TITLE
why

### ISSUE THREAD

**Issue by MyLacrosse** [WeBankBlockchain/WeBASE-Web#468]
为什么一个在线技术文档都不行

**Comment by MyLacrosse** [comment]
打不开吗

**Comment by CodingCattwo** [comment]
可使用国内镜像源的文档：
v1.5.4: https://osp-1257653870.cos.ap-guangzhou.myqcloud.com/WeBASE/doc/index.html
v3.0.2: https://osp-1257653870.cos.ap-guangzhou.myqcloud.com/WeBASE/doc/lab/index.html
