### ISSUE TITLE
release-1.5.3版本、tag v1.5.4版本、tag v1.5.5版本，启动项目后，数据大屏板块页面布局异常，没有根据浏览器大小进行自适应

### ISSUE THREAD

**Issue by dohkoxiaozu** [WeBankBlockchain/WeBASE-Web#498]
## **Version**
- release-1.5.3
- tag-v1.5.4
- tag-v1.5.5

## **Node Version**
16.17.0

## **Operating System Version**
Windows 11 22H2

## **Expected Behavior**
数据大屏页面能随浏览器大小进行自适应（不修改第三方库文件的前提下）

## **Actual Behavior**
下载项目后，安装依赖，启动项目运行，登录后，访问头部栏的《数据大屏》，然后就会发现数据大屏页面的布局没有填充满屏，改变浏览器大小后布局也不会进行适应。
![image](https://github.com/WeBankBlockchain/WeBASE-Web/assets/48460761/793befe6-902e-4bb3-a7d4-f8c85b7b06db)
![image](https://github.com/WeBankBlockchain/WeBASE-Web/assets/48460761/e5a7bdce-10e1-4420-8f0a-c17b03e4b4ec)

## **Additional Information**
但是如果是使用相对应版本的官方docker镜像进行部署，数据大屏页面的布局是会自动填充满屏的，而且会随浏览器大小进行自适应。

## **root causes**
官方上述的docker镜像部署后（如1.5.3版本），分析混淆后的代码后发现， lib-flexible 的文件里某个函数的逻辑与本地项目存在差异。

文件路径：node_modules/lib-flexible/flexible.js
官方docker版本：
```
function refreshRem() {
  var rem = docEl.clientWidth / 24;
  docEl.style.fontSize = rem + "px"
  flexible.rem = win.rem = rem
}
```
本地版本：
```
function refreshRem(){
    var width = docEl.getBoundingClientRect().width;
    if (width / dpr > 540) {
        width = width * dpr;
    }
    var rem = width / 10;
    docEl.style.fontSize = rem + 'px';
    flexible.rem = win.rem = rem;
}
```

**Comment by CodingCattwo** [comment]
请问你的webase-web是哪个版本的？并且该版本是通过什么方式部署的时候会出现不自动适应的问题？（如，一键部署、手动编译部署、docker部署）

**Comment by CodingCattwo** [comment]
可参考 issue #510 修复

**Comment by dohkoxiaozu** [comment]
> 可参考 issue #510 修复

好的，谢谢！
