### ISSUE TITLE
v1.5.5镜像版本在合约管理页切换群组时报错

### ISSUE THREAD

**Issue by dohkoxiaozu** [WeBankBlockchain/WeBASE-Web#534]
![image](https://github.com/user-attachments/assets/1aa08261-94bf-4449-8ab5-88a4fc1f810a)
![C}{~N EZ}%_6P7GXSCQOU0J](https://github.com/user-attachments/assets/651eb2b9-b356-49cf-b806-1319c1cda1dd)

问题记录：
`src/views/chaincode/contract.vue`，在切换群组后，触发 `changGroup` 方法，后续调用了不存在的方法 `checkIsWasm`，导致异常捕获后提示 “系统错误”

疑问：
请问在这个版本分支里，这个方法的缺失，是漏了这个方法的提交？还是本来就该剔除这个方法的相关逻辑的？这个错误会影响合约管理的使用吗？

相关代码截图：
![image](https://github.com/user-attachments/assets/289902f9-cf4d-4e17-b9a9-ecacf421756c)
![image](https://github.com/user-attachments/assets/8cbc9fe4-14f4-483b-b99f-995968e0d3b5)
![image](https://github.com/user-attachments/assets/812a29d2-5ea6-4785-a37d-a7aa78ce65ad)
![image](https://github.com/user-attachments/assets/b6a71a73-f1a2-46d0-a390-eaadbb766a0f)
![image](https://github.com/user-attachments/assets/4acb91a9-988b-4ca7-a68a-b975f60a8ad7)

**Comment by 724338817** [comment]
<img width="410" alt="企业微信截图_17314635272224" src="https://github.com/user-attachments/assets/2b638c98-94b8-488b-8496-ed60b4164921">
<img width="269" alt="企业微信截图_17314635399066" src="https://github.com/user-attachments/assets/ec3b5d50-ead9-4ca8-ae31-ac9d2fdfb908">

将此处的 **liquidCheckMethod** 方法替换成
```
this.initWorker();
this.getEncryption(this.querySolcList);
```
